.PHONY: clean All

All:
	@echo "----------Building project:[ Polling_Server_Thread - Debug ]----------"
	@cd "Polling_Server_Thread" && "$(MAKE)" -f  "Polling_Server_Thread.mk"
clean:
	@echo "----------Cleaning project:[ Polling_Server_Thread - Debug ]----------"
	@cd "Polling_Server_Thread" && "$(MAKE)" -f  "Polling_Server_Thread.mk" clean
