.PHONY: clean All

All:
	@echo "----------Building project:[ Server_Stream - Debug ]----------"
	@cd "Server" && "$(MAKE)" -f  "Server_Stream.mk"
clean:
	@echo "----------Cleaning project:[ Server_Stream - Debug ]----------"
	@cd "Server" && "$(MAKE)" -f  "Server_Stream.mk" clean
