.PHONY: clean All

All:
	@echo "----------Building project:[ Polling_Client - Debug ]----------"
	@cd "Polling_Client" && "$(MAKE)" -f  "Polling_Client.mk"
clean:
	@echo "----------Cleaning project:[ Polling_Client - Debug ]----------"
	@cd "Polling_Client" && "$(MAKE)" -f  "Polling_Client.mk" clean
